fixes:
  - "::dummy_dir/"
coverage:
  notify:
    slack:
      default:
        url: "secret:uVFh3vkGnyE192pC6CagtUcedrNYr45lmPBO/FnltCfTbWHVc4IxlmvMv/cnWZct4+oa2V/1E7jhH1qhcvN6tBpuTlT+3vloyOvyAQBE/if+YYhy6Pm2LelQN/oMKQDjnEoKGLpfncW18flH4W2YjQAtRcnxxkI1Kw+uxF03q4Y="
        threshold: 0.0%
